### ISSUE TITLE
[NL] Synchronisatie van bestaande gebruikers

### ISSUE THREAD

**Issue by TranceAccount** [Compizfox/Inschrijflijst#1]
**Probleem:** Verkeerde naam/e-mailadres in de inschrijflijst wordt niet aangepast zodra deze is aangepast in de AD.

**Fout:** Als de gegevens na het aanmaken van de gebruikers worden aangepast, dan wordt dit niet doorverwerkt naar de DB van de inschrijflijst.

**Tijdelijke oplossing:** Handmatig aanpassen.

-- André

**Comment by Compizfox** [comment]
Gefixt door 9b1c35a835599dec00198e0751b50f47f82b973f.
